### ISSUE TITLE
ServerboundMovePlayerPacket error when using changeDimension to fantasy dimensions, chunks do not generate

### ISSUE THREAD

**Issue by filloax** [NucleoidMC/fantasy#39]
As title. Trying the lib by using a simple command that creates a temporary dimension and moves the player there, but I just get the classic pre-loading empty world on the client side as chunks never generate, with the error at the bottom of the issue post in the log.

The command code (in Kotlin, mojmap, fabric) is this:

```Kotlin
object Commands {
    val worldConfig = { server: MinecraftServer ->
        RuntimeWorldConfig()
            .setDimensionType(BuiltinDimensionTypes.OVERWORLD)
            .setDifficulty(Difficulty.HARD)
            .setGameRule(GameRules.RULE_DAYLIGHT, false)
            .setGenerator(server.overworld().chunkSource.generator)
            .setSeed(1234L)
    }

    fun register(dispatcher: CommandDispatcher<CommandSourceStack>, registryAccess: CommandBuildContext, environment: Commands.CommandSelection) {
        //tmpdim: move to temporary dim
        dispatcher.register(literal("tmpdim").requires{ it.hasPermission(2) }
            .executes { ctx ->
                val fantasy = Fantasy.get(ctx.source.server)
                val worldHandle:= fantasy.openTemporaryWorld(worldConfig(ctx.source.server))
                val level = worldHandle.asWorld()
                ctx.source.playerOrException.changeDimension(level)

                1
            }
        )
    }
}
```

Am I doing something wrong?

```
[20:54:42] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot@380fc290, suppressing error
 java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectSet" is null
	at net.minecraft.server.level.DistanceManager.removePlayer(DistanceManager.java:225) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:1093) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:477) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:928) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:31) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:90) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:34) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.TickTask.run(TickTask.java:20) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:143) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:797) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:189) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:114) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:780) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:774) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:103) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:760) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:696) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:252) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:54:42] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos@5f723ccf, suppressing error
 java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectSet" is null
	at net.minecraft.server.level.DistanceManager.removePlayer(DistanceManager.java:225) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:1093) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:477) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:928) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:31) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:68) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:34) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.TickTask.run(TickTask.java:20) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:143) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:797) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:189) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:114) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:780) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:774) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:103) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:760) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:696) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:252) ~[minecraft-common-c4cba8cea8-1.20.2-loom.mappings.1_20_2.layered+hash.405084424-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by filloax** [comment]
For context, this is on 1.20.2, fabric ver `0.91.1+1.20.2`, fantasy ver `0.4.11+1.20-rc1`

**Comment by Clomclem** [comment]
I'm having a similar error on 1.20.4, heres the stacktrace:

```
[20:38:09] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$Full@eb73892, suppressing error
 java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectSet" is null
	at net.minecraft.server.world.ChunkTicketManager.handleChunkLeave(ChunkTicketManager.java:237) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.updatePosition(ThreadedAnvilChunkStorage.java:1085) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager.updatePosition(ServerChunkManager.java:492) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler.java:950) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket.java:29) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$Full.apply(PlayerMoveC2SPacket.java:66) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:24) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:17) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:138) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:24) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:843) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:209) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:112) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:826) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:820) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:122) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:807) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:741) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[minecraft-merged-28b5976c15-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

**Comment by Libreh** [comment]
I can re-produce this as well.

**Comment by Earthcomputer** [comment]
For custom dimensions, you are supposed to use `FabricDimensions.teleport` or `ServerPlayer.teleportTo` instead of `ServerPlayer.changeDimension`.

**Comment by Libreh** [comment]
> For custom dimensions, you are supposed to use `FabricDimensions.teleport` or `ServerPlayer.teleportTo` instead of `ServerPlayer.changeDimension`.

I forgot about this issue but yeah this fixed it for me in case anyone was wondering what the fix was/if it would work.

**Comment by CaelTheColher** [comment]
I'm having the same issue on 1.21 while using ServerPlayer.teleportTo, and Fabric Dimensions no longer exists in this version

**Comment by CaelTheColher** [comment]
Ok I'm back to having no clue. I made a command to create a dimension and another to teleport to it and that seems to work fine but then it breaks the original dimension created on server start? Even though they are two separate dimensions

**Comment by Earthcomputer** [comment]
@CaelTheColher in 1.21, `FabricDimensions.teleport` has been removed, you can just use `Entity.teleportTo`.

**Comment by CaelTheColher** [comment]
> @CaelTheColher in 1.21, `FabricDimensions.teleport` has been removed, you can just use `Entity.teleportTo`.

I am already using that, but still getting the same error as op

**Comment by CaelTheColher** [comment]
I found the problem, I was teleporting on the ServerPlayConnectionEvents.JOIN event, but that is too early and it can mess things up

**Comment by Libreh** [comment]
> I found the problem, I was teleporting on the ServerPlayConnectionEvents.JOIN event, but that is too early and it can mess things up

What I like to do is have a playerJoined UUID list and then teleport the player on next server tick, if you want compatibility with VMP you can also make sure the notInAnyWorld field is false before running anything.
